language: python
sudo: false

before_install:
  - rvm install 2.2
  - rvm use 2.2
  - gem install hiptest-publisher
  - hiptest-publisher -c robotframework.conf --only=tests --test-run-id=146099
  - pip install robotframework

script:
 - robot -P src:tests --loglevel=DEBUG tests

after_script:
  - hiptest-publisher -c robotframework.conf --push=output.xml --test-run-id=146099
